<?php if(!$auth)exit;?><style>main{padding:0;}
select,input,button{margin:0;font-size:1rem;}
select{border-radius:.3em 0 0 .3em;}
button{border-radius:0 .3em .3em 0;padding:.2em .4em;}</style>

<div style="padding:.5em;"><span style="float:right;">
<select onchange="$('fn').value='';$('code').value=this.value==''||this.value=='<?=rtrim(str_repeat('../',substr_count($dir,'/')-1),'/').$dir?>site'?'':xhr(1,{a:1,l:this.value});$('fn').style.display=this.value==''||this.value=='<?=rtrim(str_repeat('../',substr_count($dir,'/')-1),'/').$dir?>site'?'inline-block':'none';$('code').focus();"><option value="">+</option><?php function tellDir($d,$m){global $dir;
 foreach(str_replace($d.'/','',glob($d.'/*')) as $f)
 {$isdir=is_dir($d.'/'.$f);
  if($isdir)tellDir($d.'/'.$f,$m);else echo '<option value="'.$d.'/'.$f.'"'.($_POST['i']==($d.'/'.$f)?' selected':'').'>'.($m?substr($d,2).'/':'').$f.'</option>';
}}tellDir(rtrim(str_repeat('../',substr_count($dir,'/')-1),'/'),1);?>
<option disabled></option><optgroup label="Menu sites"><option value="<?=rtrim(str_repeat('../',substr_count($dir,'/')-1),'/').$dir?>site">+</option><?php tellDir(rtrim(str_repeat('../',substr_count($dir,'/')-1),'/').$dir.'site',0);?></optgroup></select><input type="text" id="fn" placeholder="Filename"<?=isset($_POST['i'])?' style="display:none;"':''?>><button onclick="if(!((!$('select')[0].selectedIndex&&$('select option[value=&quot;<?=str_repeat('../',substr_count($dir,'/')-1)?>'+$('fn').value.replace(/[\/&quot;'<>#?:]/gu,'')+'&quot;]').length)||($('select')[0].value=='<?=rtrim(str_repeat('../',substr_count($dir,'/')-1),'/').$dir?>site'&&$('select option[value=&quot;<?=rtrim(str_repeat('../',substr_count($dir,'/')-1),'/').$dir?>site/'+$('fn').value.replace(/[\/&quot;'<>#?:]/gu,'')+'&quot;]').length))||confirm('The file already exists. Do you really want to replace it?')){alert(xhr(1,{a:0,l:$('select')[0].selectedIndex?($('select')[0].value=='<?=rtrim(str_repeat('../',substr_count($dir,'/')-1),'/').$dir?>site'?$('select')[0].value+'/'+$('fn').value:$('select')[0].value):'<?=str_repeat('../',substr_count($dir,'/')-1)?>'+$('fn').value.replace(/[\/&quot;'<>#?:]/gu,''),c:$('code').value})==='1'?'File saved':'Error');if($('select')[0].value==''){$('select option[disabled]')[0].insertAdjacentHTML('beforebegin','<option class=&quot;a&quot; value=&quot;<?=str_repeat('../',substr_count($dir,'/')-1)?>'+$('fn').value+'&quot;>/'+$('fn').value+'</option>');$('.a')[0].selected=1;$('.a')[0].classList.remove('a');}else if($('select')[0].value=='<?=rtrim(str_repeat('../',substr_count($dir,'/')-1),'/').$dir?>site'){$('select optgroup')[0].insertAdjacentHTML('beforeend','<option value=&quot;'+$('select')[0].value+'/'+$('fn').value+'&quot;>'+$('fn').value+'</option>');$('select option')[$('select option').length-1].selected=1;}$('fn').style.display='none';}">Save</button>
</span><h1 style="margin:.5rem 1rem;">Editor</h1></div>

<textarea id="code" style="margin:0;width:100%;height:calc(100vh - 4.5rem - 1px);box-sizing:border-box;border:0;padding:.4em;font:12px Menlo Regular,Consolas,Andale Mono,sans-serif;border-top:1px solid #888;resize:none;"><?=isset($_POST['i'])?file_get_contents($_POST['i']):''?></textarea>

<script>$('code').focus();</script>